server:
  port: 8080
  servlet:
    context-path: /api/v1
logging:
  level:
    root: WARN
    es:
      parravidales:
        tasks: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
